version: "3"
services:
  client:
    image: yandex/clickhouse-client
    container_name: tz1-clickhouse-client
    command: ['--host', 'server']
  server:
    image: yandex/clickhouse-server
    container_name: tz1-clickhouse-server
    ports:
      - "8193:8123"
      - "9090:9000"
      - "9099:9009"

  nginx:
    image: nginx:latest
    ports:
        - "4380:80"
        - "4443:443"
    volumes:
        - ./hosts:/etc/nginx/conf.d
        - ./logs:/var/log/nginx
        - ./:/var/www
    links:
        - php

  php:
    build: .
    container_name: tz1-php
    ports:
      - 8090:80
    entrypoint: bash -c "echo -e \"`/sbin/ip route|awk '/default/ { print $$3 }'`\thost.docker.internal\" | tee -a /etc/hosts > /dev/null && /usr/local/bin/docker-php-entrypoint -k start"
    volumes:
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./:/var/www
    depends_on:
      - client
      - server
